portfolioList = [
    {
        id: "0",
        web: "true",
        nft: "false",
        title: "누리체인",
        desc: "블록체인 한글 교육 플랫폼",
        thumbnail: "nurichain_thumb.jpg",
        favicon: "nurichain_fav.png",
        screenshot: "nurichain.jpg",
        client: "이카이스",
        time: "2023.10 - 2023.10",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(자체 개발, 소스코드 원본 전달), 다국어(한국어, 영어) 지원, 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "1",
        web: "true",
        nft: "false",
        title: "FiNote",
        desc: "블로그 기반 AI 학습 서비스",
        thumbnail: "finote_thumb.jpg",
        favicon: "finote_fav.png",
        screenshot: "finote.jpg",
        client: "METEOR Team",
        time: "2023.11 - 2023.11",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(자체 개발, 소스코드 원본 전달), Lottie 애니메이션 제작 및 삽입, 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "2",
        web: "true",
        nft: "true",
        title: "신수",
        desc: "전략 RPG NFT 프로젝트",
        thumbnail: "sinsu_thumb.jpg",
        favicon: "sinsu_fav.png",
        screenshot: "sinsu.jpg",
        client: "언커먼즈",
        time: "2022.12 - 2023.01",
        task: "프로젝트 소개 반응형 웹사이트 개발, NFT 이미지 및 메타데이터 조합, 폴리곤(Polygon) 네트워크 기반의 NFT(ERC721A) 스마트컨트랙트 개발, 반응형 민팅페이지 개발 및 연동, 온체인(Onchain) NFT 육성 시스템 개발",
    },
    {
        id: "3",
        web: "true",
        nft: "false",
        title: "다올림리뷰",
        desc: "최저가 블로그 체험단 플랫폼",
        thumbnail: "daolimreview_thumb.jpg",
        favicon: "daolimreview_fav.png",
        screenshot: "daolimreview.jpg",
        client: "에이원컴퍼니",
        time: "2023.04 - 2023.05",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(자체 개발, 소스코드 원본 전달), DB 수집용 문의하기 기능 제공, 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "4",
        web: "true",
        nft: "true",
        title: "페르소나",
        desc: "콘텐츠 IP NFT 리뷰 플랫폼",
        thumbnail: "persona_thumb.jpg",
        favicon: "persona_fav.png",
        screenshot: "persona.jpg",
        client: "언커먼즈",
        time: "2022.12 - 2023.01",
        task: "플랫폼 반응형 웹사이트 개발(Mobile First UI/UX Design), 온체인(Onchain) 리뷰 시스템 개발, 플랫폼 - 블록체인 스마트컨트랙트 연동",
    },
    {
        id: "5",
        web: "true",
        nft: "false",
        title: "RCS",
        desc: "서울 소재 비인가 국제학교",
        thumbnail: "rcs_thumb.jpg",
        favicon: "rcs_fav.png",
        screenshot: "rcs.jpg",
        client: "루즈벨트컬리짓서울",
        time: "2023.07 - 2023.07",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(자체 개발, 소스코드 원본 전달), 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "6",
        web: "true",
        nft: "true",
        title: "하이드아웃",
        desc: "Web 3.0 패션 NFT 프로젝트",
        thumbnail: "hideout_thumb.jpg",
        favicon: "hideout_fav.png",
        screenshot: "hideout.jpg",
        client: "하이드아웃",
        time: "2022.12 - 2023.01",
        task: "프로젝트 소개 반응형 웹사이트 개발, NFT 이미지 및 메타데이터 조합, 이더리움(Ethereum) 네트워크 기반의 NFT(ERC721A) 스마트컨트랙트 개발, 반응형 민팅페이지 개발 및 연동, NFT 운영·관리 가이드 제공",
    },
    {
        id: "7",
        web: "true",
        nft: "true",
        title: "도니캣",
        desc: "상업적 IP PFP NFT 프로젝트",
        thumbnail: "donicat_thumb.jpg",
        favicon: "donicat_fav.png",
        screenshot: "donicat.jpg",
        client: "워크도니",
        time: "2022.08 - 2022.09",
        task: "프로젝트 소개 반응형 웹사이트 개발, 폴리곤(Polygon) 네트워크 기반의 NFT(ERC721A) 스마트컨트랙트 개발, 반응형 민팅페이지 개발 및 연동, NFT 홀더 증명 및 리워드 시스템 개발, NFT 및 토큰 운영·관리 가이드 제공",
    },
    {
        id: "8",
        web: "true",
        nft: "false",
        title: "코멘터리사무소",
        desc: "온라인 콘텐츠 개발 스튜디오",
        thumbnail: "commentaryoffice_thumb.jpg",
        favicon: "commentaryoffice_fav.png",
        screenshot: "commentaryoffice.jpg",
        client: "코멘터리사무소",
        time: "2023.06 - 2023.07",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(자체 개발, 소스코드 원본 전달), DB 수집용 문의하기 기능 제공, 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "9",
        web: "true",
        nft: "false",
        title: "다비드몰",
        desc: "중장년 남성 건강식품 쇼핑몰",
        thumbnail: "davidmall_thumb.jpg",
        favicon: "davidmall_fav.png",
        screenshot: "davidmall.jpg",
        client: "튼튼한사람들",
        time: "2022.08 - 2022.09",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(카페24 쇼핑몰 커스터마이징), 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "10",
        web: "true",
        nft: "true",
        title: "나비 NAVi",
        desc: "멤버십 PFP NFT 프로젝트",
        thumbnail: "louiscatsnavi_thumb.jpg",
        favicon: "louiscatsnavi_fav.png",
        screenshot: "louiscatsnavi.jpg",
        client: "루이스 캣츠 나비",
        time: "2022.07 - 2022.08",
        task: "프로젝트 소개 반응형 웹사이트 개발, NFT 이미지 및 메타데이터 조합, 클레이튼(Klaytn) 네트워크 기반의 NFT(KIP17) 스마트컨트랙트 개발, 반응형 민팅페이지 개발 및 연동, NFT 운영·관리 가이드 제공",
    },
    {
        id: "11",
        web: "true",
        nft: "false",
        title: "아이고마트",
        desc: "유튜브 채널 「리첸쿡」 쇼핑몰",
        thumbnail: "igomart_thumb.jpg",
        favicon: "igomart_fav.png",
        screenshot: "igomart.jpg",
        client: "튼튼한사람들",
        time: "2023.10 - 2023.11",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(카페24 쇼핑몰 커스터마이징), 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "12",
        web: "false",
        nft: "true",
        title: "파라버스",
        desc: "AR 메타버스 프로젝트",
        thumbnail: "paraverse_thumb.jpg",
        favicon: "paraverse_fav.png",
        screenshot: "paraverse.jpg",
        client: "이매지니어스",
        time: "2023.03 - 2023.04",
        task: "이더리움(Ethereum) 네트워크 기반의 NFT(ERC721A) 스마트컨트랙트 개발, 반응형 민팅페이지 개발 및 연동, NFT 운영·관리 가이드 제공",
    },
    {
        id: "13",
        web: "true",
        nft: "false",
        title: "파인드뷰티",
        desc: "헤어스타일 추천 AI 솔루션",
        thumbnail: "findbeauty_thumb.jpg",
        favicon: "findbeauty_fav.png",
        screenshot: "findbeauty.jpg",
        client: "파인드뷰티",
        time: "2023.04 - 2023.05",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 모바일 퍼스트 웹사이트 개발(자체 개발, 소스코드 원본 전달), 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "14",
        web: "true",
        nft: "false",
        title: "에듀그라운드",
        desc: "찾아가는 대학생 진로 특강",
        thumbnail: "eduground_thumb.jpg",
        favicon: "eduground_fav.png",
        screenshot: "eduground.jpg",
        client: "에듀그라운드",
        time: "2022.12 - 2023.01",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(자체 개발, 소스코드 원본 전달), 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "15",
        web: "false",
        nft: "true",
        title: "마이크로 서울",
        desc: "페스티벌 티켓 NFT 프로젝트",
        thumbnail: "microseoul2022_thumb.jpg",
        favicon: "microseoul2022_fav.png",
        screenshot: "microseoul2022.jpg",
        client: "방송식당",
        time: "2022.07 - 2022.08",
        task: "클레이튼(Klaytn) 네트워크 기반의 NFT(KIP17) 스마트컨트랙트 개발, 반응형 민팅페이지 개발 및 연동, NFT 운영·관리 가이드 제공",
    },
    {
        id: "16",
        web: "false",
        nft: "true",
        title: "마온 : 온도리",
        desc: "멘탈케어 PFP NFT 프로젝트",
        thumbnail: "ondori_thumb.jpg",
        favicon: "ondori_fav.png",
        screenshot: "ondori.jpg",
        client: "모두좋아진다",
        time: "2022.11 - 2022.12",
        task: "이더리움(Ethereum) 네트워크 기반의 NFT(ERC721A) 스마트컨트랙트 개발, 반응형 민팅페이지 개발 및 연동, NFT 운영·관리 가이드 제공",
    },
    {
        id: "17",
        web: "true",
        nft: "false",
        title: "미디어와이드",
        desc: "영상 제작 에이전시",
        thumbnail: "mediawide_thumb.jpg",
        favicon: "mediawide_fav.png",
        screenshot: "mediawide.jpg",
        client: "미디어와이드",
        time: "2022.08 - 2022.09",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(자체 개발, 소스코드 원본 전달), DB 수집용 문의하기 기능 제공, 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "18",
        web: "false",
        nft: "true",
        title: "강치유니언",
        desc: "수익쉐어 PFP NFT프로젝트",
        thumbnail: "gangchiunion_thumb.jpg",
        favicon: "gangchiunion_fav.png",
        screenshot: "gangchiunion.jpg",
        client: "라카이코리아",
        time: "2022.11 - 2022.12",
        task: "폴리곤(Polygon) 네트워크 기반의 NFT(ERC721A) 스마트컨트랙트 개발, 반응형 민팅페이지 개발 및 연동, NFT 운영·관리 가이드 제공",
    },
    {
        id: "19",
        web: "true",
        nft: "false",
        title: "밈보 포 스피드",
        desc: "방치형 채굴 디파이 프로젝트",
        thumbnail: "mimboforspeed_thumb.jpg",
        favicon: "mimboforspeed_fav.png",
        screenshot: "mimboforspeed.jpg",
        client: "헨즈엑스",
        time: "2023.09 - 2023.09",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(자체 개발, 소스코드 원본 전달), 다국어(한국어, 영어, 일본어 등 7개) 지원, 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "20",
        web: "true",
        nft: "false",
        title: "애드쿼티",
        desc: "성과제 인플루언서 광고 플랫폼",
        thumbnail: "adequity_thumb.jpg",
        favicon: "adequity_fav.png",
        screenshot: "adequity.jpg",
        client: "임가네",
        time: "2023.06 - 2023.06",
        task: "웹사이트 기획(텍스트 및 리소스 정리), UI/UX 디자인(Adobe XD, Figma), 반응형 웹사이트 개발(자체 개발, 소스코드 원본 전달), DB 수집용 문의하기 기능 제공, 기본 SEO 및 SNS 공유 링크 작업",
    },
    {
        id: "21",
        web: "false",
        nft: "true",
        title: "제네시스 코어",
        desc: "콘텐츠 IP NFT 프로젝트",
        thumbnail: "genesiscore_thumb.jpg",
        favicon: "genesiscore_fav.png",
        screenshot: "genesiscore.jpg",
        client: "제이제이스튜디오",
        time: "2022.09 - 2022.10",
        task: "이더리움(Ethereum) 네트워크 기반의 NFT(ERC721A) 스마트컨트랙트 개발, 반응형 민팅페이지 개발 및 연동, NFT 운영·관리 가이드 제공",
    },
]